name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_URI: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/traccar-lambda:latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'jcardus/traccar'
          ref: 'master'
          path: traccar

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build traccar
        working-directory: traccar
        run: ./gradlew build --no-daemon -x checkstyleMain

      - name: Build lambda
        run: ./gradlew build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_URI }}
          provenance: false   # ← disables BuildKit attestation metadata (required for Lambda)
          sbom: false         # ← disables build metadata that may break Lambda

      - name: Update lambda
        run: >
          aws lambda update-function-code
          --function-name ${{ vars.FUNCTION_NAME }}
          --image-uri ${{ env.IMAGE_URI }}
          --no-cli-pager
      - name: Wait for lambda update
        run: >
          aws lambda wait function-updated
          --function-name ${{ vars.FUNCTION_NAME }}

