name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4
        with:
          repository: 'jcardus/traccar'
          ref: 'master'
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew build --no-daemon
      - name: Build installers
        working-directory: ./setup
        run: |
          docker build --platform linux/amd64 -t traccar-lambda .
          sudo apt-get install makeself
          wget -q https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.2+13/OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz
          mkdir -p out/{conf,data,lib,logs,web,schema,templates}
          cp ../target/tracker-server.jar out
          cp ../target/lib/* out/lib
          cp ../schema/* out/schema
          cp -r ../templates/* out/templates
          cp setup.sh out
          cp traccar.service out
          tar -xf OpenJDK21U-jdk_x64_linux_hotspot_21.0.2_13.tar.gz
          jlink --module-path jdk-*/jmods --add-modules java.se,jdk.charsets,jdk.crypto.ec,jdk.unsupported --output out/jre
          rm -rf jdk-*
          makeself --needroot --quiet --notemp out traccar.run "traccar" ./setup.sh
          mkdir deploy
          mv traccar.run deploy

      - name: docker
        run: |
          docker build --platform linux/amd64 -t traccar-lambda .
          aws ecr get-login-password --profile entrack | docker login --username AWS --password-stdin 533267349510.dkr.ecr.us-east-1.amazonaws.com
          docker tag traccar-lambda:latest 533267349510.dkr.ecr.us-east-1.amazonaws.com/traccar-lambda
          docker push 533267349510.dkr.ecr.us-east-1.amazonaws.com/traccar-lambda
          aws lambda update-function-code \
          --function-name traccar-lambda \
          --image-uri 533267349510.dkr.ecr.us-east-1.amazonaws.com/traccar-lambda:latest \
          --profile entrack \
          --no-cli-pager
          echo "waiting..."
          aws lambda wait function-updated \
          --function-name traccar-lambda \
          --profile entrack

